version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user-service:
    build: ./user-service
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: todo_db
      DB_PORT: 5432
    depends_on:
      - postgres
    ports:
      - "50051:50051"

  task-service:
    build: ./task-service
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: todo_db
      DB_PORT: 5432
    depends_on:
      - user-service
      - postgres
    ports:
      - "50052:50052"
      - "8081:8081"

volumes:
  pgdata:
