// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: common/proto/apigateway.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	proto1 "github.com/tlsh0/grpc-todo-list/task-service/proto"
	unsafe "unsafe"
	proto "github.com/tlsh0/grpc-todo-list/user-service/proto"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_common_proto_apigateway_proto protoreflect.FileDescriptor

const file_common_proto_apigateway_proto_rawDesc = "" +
	"\n" +
	"\x1dcommon/proto/apigateway.proto\x12\n" +
	"apigateway\x1a\x1cgoogle/api/annotations.proto\x1a\x17common/proto/user.proto\x1a\x17common/proto/task.proto2\x96\x04\n" +
	"\x11ApiGatewayService\x12X\n" +
	"\fRegisterUser\x12\x15.user.RegisterRequest\x1a\x12.user.AuthResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/users/register\x12O\n" +
	"\tLoginUser\x12\x12.user.LoginRequest\x1a\x12.user.AuthResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/users/login\x12O\n" +
	"\n" +
	"CreateTask\x12\x17.task.CreateTaskRequest\x1a\x12.task.TaskResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/tasks\x12N\n" +
	"\tListTasks\x12\x16.task.ListTasksRequest\x1a\x16.task.TaskListResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/tasks\x12\\\n" +
	"\fCompleteTask\x12\x19.task.CompleteTaskRequest\x1a\x12.task.TaskResponse\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/tasks/complete\x12W\n" +
	"\n" +
	"DeleteTask\x12\x17.task.DeleteTaskRequest\x1a\x18.task.DeleteTaskResponse\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/tasks/{id}B\x1aZ\x18apigateway-service/protob\x06proto3"

var file_common_proto_apigateway_proto_goTypes = []any{
	(*proto.RegisterRequest)(nil),      // 0: user.RegisterRequest
	(*proto.LoginRequest)(nil),         // 1: user.LoginRequest
	(*proto1.CreateTaskRequest)(nil),   // 2: task.CreateTaskRequest
	(*proto1.ListTasksRequest)(nil),    // 3: task.ListTasksRequest
	(*proto1.CompleteTaskRequest)(nil), // 4: task.CompleteTaskRequest
	(*proto1.DeleteTaskRequest)(nil),   // 5: task.DeleteTaskRequest
	(*proto.AuthResponse)(nil),         // 6: user.AuthResponse
	(*proto1.TaskResponse)(nil),        // 7: task.TaskResponse
	(*proto1.TaskListResponse)(nil),    // 8: task.TaskListResponse
	(*proto1.DeleteTaskResponse)(nil),  // 9: task.DeleteTaskResponse
}
var file_common_proto_apigateway_proto_depIdxs = []int32{
	0, // 0: apigateway.ApiGatewayService.RegisterUser:input_type -> user.RegisterRequest
	1, // 1: apigateway.ApiGatewayService.LoginUser:input_type -> user.LoginRequest
	2, // 2: apigateway.ApiGatewayService.CreateTask:input_type -> task.CreateTaskRequest
	3, // 3: apigateway.ApiGatewayService.ListTasks:input_type -> task.ListTasksRequest
	4, // 4: apigateway.ApiGatewayService.CompleteTask:input_type -> task.CompleteTaskRequest
	5, // 5: apigateway.ApiGatewayService.DeleteTask:input_type -> task.DeleteTaskRequest
	6, // 6: apigateway.ApiGatewayService.RegisterUser:output_type -> user.AuthResponse
	6, // 7: apigateway.ApiGatewayService.LoginUser:output_type -> user.AuthResponse
	7, // 8: apigateway.ApiGatewayService.CreateTask:output_type -> task.TaskResponse
	8, // 9: apigateway.ApiGatewayService.ListTasks:output_type -> task.TaskListResponse
	7, // 10: apigateway.ApiGatewayService.CompleteTask:output_type -> task.TaskResponse
	9, // 11: apigateway.ApiGatewayService.DeleteTask:output_type -> task.DeleteTaskResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_apigateway_proto_init() }
func file_common_proto_apigateway_proto_init() {
	if File_common_proto_apigateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_apigateway_proto_rawDesc), len(file_common_proto_apigateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_proto_apigateway_proto_goTypes,
		DependencyIndexes: file_common_proto_apigateway_proto_depIdxs,
	}.Build()
	File_common_proto_apigateway_proto = out.File
	file_common_proto_apigateway_proto_goTypes = nil
	file_common_proto_apigateway_proto_depIdxs = nil
}
